"""Add maximum HP to a monster.

Revision ID: 12841eb2982f
Revises: 83cea33c2cd2
Create Date: 2019-11-16 12:29:44.844277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12841eb2982f'
down_revision = '83cea33c2cd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monster', sa.Column('maximum_hp', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monster', 'maximum_hp')
    # ### end Alembic commands ###
